name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - develop
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    name: Build Project Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          make --directory docs install
      - name: Build the docs
        run: |
          make --directory docs build
      - name: Upload GitHub Pages artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # 3.0.1
        with:
          name: github-pages
          path: docs/build/dirhtml/
          retention-days: 3
  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy uploaded artifact
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
